### ISSUE TITLE
I think it should be this.log_level

### ISSUE THREAD

**Issue by gobinath2389** [ishtms/learn-nodejs-hard-way#17]
https://github.com/ishtms/learn-nodejs-hard-way/blame/051798fb90cf5c16e2bd7a0407df3b5931a06325/chapters/ch04-logtar-our-logging-library.md#L193

**Comment by ishtms** [comment]
The member variable is `#level`. The `log_level` was actually a typo from my side on the markdown/chapter. You can find the final code of that chapter [here](https://github.com/ishtms/learn-nodejs-hard-way/tree/master/code/chapter_04)

Thanks. @gobinath2389
