### ISSUE TITLE
Part of code will not work

### ISSUE THREAD

**Issue by MarkoMlinarevicDept** [ishtms/learn-nodejs-hard-way#27]
https://github.com/ishtms/learn-nodejs-hard-way/blob/b3b652ebddc23295446cfc3c5185438018cc599b/chapters/ch04.2-writing-logs.md?plain=1#L488C1-L498C4

This code needs to be corrected it will not work.

**Comment by ishtms** [comment]
@MarkoMlinarevicDept Thanks. Can you explain what the issue is?

**Comment by marko-mlinarevic** [comment]
If await must be in async function or at the top of file itself before everything, otherwise you get error
