### ISSUE TITLE
Duplicate '# Table of contents' Header Generated in Readme.md by ./getIndex.js Automation

### ISSUE THREAD

**Issue by lucaspicinini** [ishtms/learn-nodejs-hard-way#54]
**Describe the bug**
Your script automation - `./getIndex.js` -  is generating two title strings - "# Table of contents" - for the Readme.md automation.

**To Reproduce**
Just run the automation or see in the repo Readme.md right now.

**Screenshots**
![image](https://github.com/user-attachments/assets/36d014c5-c3fa-493e-a175-ee6e19e117f3)

**Expected behavior**
Just one Readme.md title being generated.

**Sugestions**
- make the string `let toc = "# Table of contents\n\n";` empty in getIndex.js: `let toc = "";`
- or just remove `# Table of contents` in the template file Readme.tl

**Comment by ishtms** [comment]
@lucaspicinini thanks, I almost forgot checking the readme after.
